# Generated by Django 4.2.23 on 2025-08-12 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='sobrenome')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica se o usuário pode acessar a área administrativa.', verbose_name='é da equipe?')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se este usuário deve ser tratado como ativo.', verbose_name='está ativo?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('desativado_por_arquivamento', models.BooleanField(default=False, help_text='Marcado automaticamente quando a prefeitura é arquivada.')),
                ('is_master', models.BooleanField(default=False, help_text='Administrador da prefeitura (pode gerenciar usuários e dados).')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
        ),
    ]
