# Generated by Django 4.2.23 on 2025-08-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('aaa_usuarios', '0001_initial'),
        ('sepultados_gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='prefeitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='sepultados_gestao.prefeitura', verbose_name='prefeitura vinculada'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
