# Generated by Django 4.2.23 on 2025-08-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0005_alter_concessaocontrato_usuario_registro_and_more'),
        ('aaa_usuarios', '0002_alter_usuario_date_joined_alter_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='prefeitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='sepultados_gestao.prefeitura', verbose_name='prefeitura vinculada'),
        ),
    ]
