# Generated by Django 5.2.3 on 2025-08-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa_usuarios', '0003_usuario_prefeitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_master',
            field=models.BooleanField(default=False, help_text='Administrador da prefeitura (pode gerenciar usuários e dados).'),
        ),
    ]
