# Generated by Django 4.2.23 on 2025-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa_usuarios', '0004_usuario_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='desativado_por_arquivamento',
            field=models.BooleanField(default=False, help_text='Marcado automaticamente quando a prefeitura é arquivada.'),
        ),
    ]
