# Generated by Django 4.2.23 on 2025-07-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepultado',
            name='importado',
            field=models.BooleanField(default=False, verbose_name='Importado via planilha'),
        ),
    ]
