# Generated by Django 4.2.23 on 2025-08-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumulo',
            name='tipo_estrutura',
            field=models.CharField(choices=[('tumulo', 'Túmulo'), ('perpetua', 'Perpétua'), ('sepultura', 'Sepultura'), ('jazigo', 'Jazigo'), ('gaveta', 'Gaveta'), ('outro', 'Outro')], default='tumulo', max_length=20, verbose_name='Tipo de estrutura'),
        ),
    ]
