# Generated by Django 5.2.3 on 2025-07-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='sepultados_gestao.concessaocontrato', verbose_name='Contrato'),
        ),
    ]
