# Generated by Django 4.2.23 on 2025-08-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0002_alter_tumulo_tipo_estrutura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translado',
            name='destino',
            field=models.CharField(choices=[('outro_tumulo', 'Outro Túmulo'), ('outro_cemiterio', 'Outro Cemitério')], max_length=20),
        ),
    ]
