# Generated by Django 5.2.3 on 2025-07-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0002_receita_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='contrato',
        ),
    ]
