# Generated by Django 4.2.23 on 2025-08-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0003_alter_translado_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadra',
            name='grid_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quadra',
            name='poligono_mapa',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
