# Generated by Django 5.2.3 on 2025-07-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0003_remove_receita_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='contrato',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sepultados_gestao.concessaocontrato'),
        ),
    ]
