# Generated by Django 5.2.3 on 2025-08-05 01:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0003_emailconfirmacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPrefeituraPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=25)),
                ('responsavel', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=30)),
                ('logradouro', models.CharField(max_length=255)),
                ('endereco_numero', models.CharField(max_length=10)),
                ('endereco_bairro', models.CharField(max_length=100)),
                ('endereco_cidade', models.CharField(max_length=100)),
                ('endereco_estado', models.CharField(max_length=2)),
                ('endereco_cep', models.CharField(max_length=15)),
                ('plano_id', models.PositiveIntegerField()),
                ('duracao_anos', models.PositiveIntegerField(default=1)),
                ('logo_base64', models.TextField(blank=True, null=True)),
                ('brasao_base64', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
