# Generated by Django 4.2.23 on 2025-08-05 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sepultados_gestao', '0004_cadastroprefeiturapendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessaocontrato',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
        migrations.AlterField(
            model_name='prefeitura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefeituras_gerenciadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
    ]
