# Generated by Django 4.2.23 on 2025-07-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0004_receita_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sepultado',
            options={'verbose_name': 'Sepultado', 'verbose_name_plural': 'Sepultados'},
        ),
        migrations.AddField(
            model_name='sepultado',
            name='cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='sepultado',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='sepultado',
            name='forma_pagamento',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('avista', 'À Vista'), ('parcelado', 'Parcelado')], default='gratuito', max_length=10, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='sepultado',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='sepultado',
            name='numero_sepultamento',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Número do sepultamento'),
        ),
        migrations.AddField(
            model_name='sepultado',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AddField(
            model_name='sepultado',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='sepultado',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
    ]
