# Generated by Django 4.2.23 on 2025-08-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0004_quadra_grid_params_quadra_poligono_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemiterio',
            name='limites_mapa',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tumulo',
            name='localizacao',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
