# Generated by Django 4.2.23 on 2025-08-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0005_alter_concessaocontrato_usuario_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefeitura',
            name='logo',
        ),
    ]
