# Generated by Django 4.2.23 on 2025-07-14 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sepultados_gestao', '0005_alter_sepultado_options_sepultado_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/', verbose_name='Arquivo')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição ou Nome do Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Envio')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
    ]
