# Generated by Django 4.2.23 on 2025-09-01 19:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0005_cemiterio_limites_mapa_tumulo_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumulo',
            name='comprimento_m',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Comprimento do túmulo em metros. Padrão: 2,00 m.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Comprimento (m)'),
        ),
        migrations.AddField(
            model_name='tumulo',
            name='largura_m',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Largura do túmulo em metros. Padrão: 1,00 m.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Largura (m)'),
        ),
    ]
