# Generated by Django 4.2.23 on 2025-07-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0006_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepultado',
            name='cpf_sepultado',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF'),
        ),
    ]
