# Generated by Django 5.2.3 on 2025-08-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0006_remove_prefeitura_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepultado',
            name='ordem_no_tumulo',
        ),
    ]
