# Generated by Django 4.2.23 on 2025-09-01 19:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0006_tumulo_comprimento_m_tumulo_largura_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumulo',
            name='angulo_graus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para herdar o ângulo da quadra.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-360.00')), django.core.validators.MaxValueValidator(Decimal('360.00'))], verbose_name='Ângulo do túmulo (°)'),
        ),
    ]
