# Generated by Django 4.2.23 on 2025-07-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0007_sepultado_cpf_sepultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumulo',
            name='cemiterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sepultados_gestao.cemiterio', verbose_name='Cemitério'),
        ),
    ]
