# Generated by Django 4.2.23 on 2025-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0007_remove_sepultado_ordem_no_tumulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemiterio',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arquivado em'),
        ),
        migrations.AddField(
            model_name='cemiterio',
            name='motivo_arquivamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do arquivamento'),
        ),
        migrations.AddField(
            model_name='cemiterio',
            name='situacao',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('arquivado', 'Arquivado')], db_index=True, default='ativo', max_length=12, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='prefeitura',
            name='arquivada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arquivada em'),
        ),
        migrations.AddField(
            model_name='prefeitura',
            name='motivo_arquivamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do arquivamento'),
        ),
        migrations.AddField(
            model_name='prefeitura',
            name='situacao',
            field=models.CharField(choices=[('ativo', 'Ativa'), ('arquivado', 'Arquivada'), ('suspenso', 'Suspensa')], db_index=True, default='ativo', max_length=12, verbose_name='Situação'),
        ),
    ]
