# Generated by Django 4.2.23 on 2025-09-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0007_tumulo_angulo_graus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadra',
            name='grid_params',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='poligono_mapa',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
