# Generated by Django 4.2.23 on 2025-07-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0008_alter_tumulo_cemiterio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaosepultado',
            name='destino_tipo',
            field=models.CharField(choices=[('INTERNO', 'Outro túmulo no mesmo cemitério'), ('EXTERNO', 'Outro cemitério'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20, verbose_name='Tipo de destino'),
        ),
    ]
