# Generated by Django 4.2.23 on 2025-07-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0009_alter_movimentacaosepultado_destino_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepultado',
            name='tumulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sepultados_gestao.tumulo', verbose_name='Túmulo'),
        ),
    ]
