# Generated by Django 4.2.23 on 2025-07-18 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0010_alter_sepultado_tumulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exumacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exumacao', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('GRATUITO', 'Gratuito'), ('PAGO', 'Pago')], default='GRATUITO', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=20, unique=True)),
                ('sepultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sepultados_gestao.sepultado')),
                ('tumulo_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sepultados_gestao.tumulo')),
            ],
        ),
        migrations.CreateModel(
            name='Translado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_translado', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('GRATUITO', 'Gratuito'), ('PAGO', 'Pago')], default='GRATUITO', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=20, unique=True)),
                ('sepultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sepultados_gestao.sepultado')),
                ('tumulo_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translado_destino', to='sepultados_gestao.tumulo')),
                ('tumulo_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translado_origem', to='sepultados_gestao.tumulo')),
            ],
        ),
        migrations.RemoveField(
            model_name='receita',
            name='movimentacao',
        ),
        migrations.DeleteModel(
            name='MovimentacaoSepultado',
        ),
        migrations.AddField(
            model_name='receita',
            name='exumacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='sepultados_gestao.exumacao', verbose_name='Exumação'),
        ),
        migrations.AddField(
            model_name='receita',
            name='translado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='sepultados_gestao.translado', verbose_name='Translado'),
        ),
    ]
