# Generated by Django 4.2.23 on 2025-07-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0011_exumacao_translado_remove_receita_movimentacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exumacao',
            options={'verbose_name': 'Exumação', 'verbose_name_plural': 'Exumações'},
        ),
        migrations.AlterModelOptions(
            name='translado',
            options={'verbose_name': 'Translado', 'verbose_name_plural': 'Translados'},
        ),
        migrations.AddField(
            model_name='exumacao',
            name='cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='exumacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='exumacao',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='exumacao',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AddField(
            model_name='exumacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='translado',
            name='cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='translado',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='translado',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='translado',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas'),
        ),
        migrations.AddField(
            model_name='translado',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='exumacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('avista', 'À Vista'), ('parcelado', 'Parcelado')], default='gratuito', max_length=10, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='exumacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='translado',
            name='forma_pagamento',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('avista', 'À Vista'), ('parcelado', 'Parcelado')], default='gratuito', max_length=10, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='translado',
            name='tumulo_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translados_destino', to='sepultados_gestao.tumulo'),
        ),
        migrations.AlterField(
            model_name='translado',
            name='tumulo_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translados_origem', to='sepultados_gestao.tumulo'),
        ),
        migrations.AlterField(
            model_name='translado',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
    ]
