# Generated by Django 4.2.23 on 2025-07-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0012_alter_exumacao_options_alter_translado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translado',
            options={'verbose_name': 'Translado', 'verbose_name_plural': 'Traslados'},
        ),
        migrations.RenameField(
            model_name='exumacao',
            old_name='data_exumacao',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='translado',
            old_name='data_translado',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='exumacao',
            name='tumulo_origem',
        ),
        migrations.RemoveField(
            model_name='translado',
            name='tumulo_origem',
        ),
        migrations.AddField(
            model_name='exumacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translado',
            name='destino',
            field=models.CharField(choices=[('outro_tumulo', 'Outro Túmulo'), ('outro_cemiterio', 'Outro Cemitério'), ('ossario', 'Ossário')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translado',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exumacao',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exumacao',
            name='numero_documento',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='exumacao',
            name='sepultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sepultados_gestao.sepultado'),
        ),
        migrations.AlterField(
            model_name='translado',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translado',
            name='numero_documento',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='translado',
            name='sepultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sepultados_gestao.sepultado'),
        ),
        migrations.AlterField(
            model_name='translado',
            name='tumulo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sepultados_gestao.tumulo'),
        ),
    ]
