# Generated by Django 4.2.23 on 2025-07-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0013_alter_translado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exumacao',
            name='tumulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sepultados_gestao.tumulo', verbose_name='Túmulo de Origem'),
        ),
    ]
