# Generated by Django 4.2.23 on 2025-07-19 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0014_exumacao_tumulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exumacao',
            name='prefeitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sepultados_gestao.prefeitura'),
        ),
    ]
