# Generated by Django 4.2.23 on 2025-07-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0015_exumacao_prefeitura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exumacao',
            name='prefeitura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sepultados_gestao.prefeitura'),
            preserve_default=False,
        ),
    ]
