# Generated by Django 4.2.23 on 2025-07-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0016_alter_exumacao_prefeitura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='exumacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='sepultados_gestao.exumacao', verbose_name='Exumação'),
        ),
    ]
