# Generated by Django 4.2.23 on 2025-07-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0018_alter_receita_translado'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='sepultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='sepultados_gestao.sepultado', verbose_name='Sepultado'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='sepultados_gestao.concessaocontrato', verbose_name='Contrato'),
        ),
    ]
