# Generated by Django 4.2.23 on 2025-07-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0019_receita_sepultado_alter_receita_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='translado',
            name='cemiterio_endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço do Cemitério'),
        ),
        migrations.AddField(
            model_name='translado',
            name='cemiterio_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cemitério'),
        ),
    ]
