# Generated by Django 4.2.23 on 2025-07-21 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sepultados_gestao', '0020_translado_cemiterio_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado'), ('excluido', 'Excluído')], max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('representacao', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('prefeitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sepultados_gestao.prefeitura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-data_hora'],
                'permissions': [],
            },
        ),
    ]
