# Generated by Django 4.2.23 on 2025-07-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0021_registroauditoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroAuditoria',
        ),
    ]
