# Generated by Django 4.2.23 on 2025-07-22 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sepultados_gestao', '0022_delete_registroauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('add', 'Adição'), ('change', 'Edição'), ('delete', 'Exclusão')], max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('representacao', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sepultados_gestao.prefeitura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
