# Generated by Django 4.2.23 on 2025-07-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepultados_gestao', '0023_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepultado',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='sepultado',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Pai'),
        ),
    ]
